
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;

import javax.xml.namespace.QName;

import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-10-13T14:16:26.594+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class WRServiceSoap_WRServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WRService");

    private static JdbcTemplate jdbctemp;
    
    private WRServiceSoap_WRServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WRService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WRService ss = new WRService(wsdlURL, SERVICE_NAME);
        WRServiceSoap port = ss.getWRServiceSoap12();  
        
        {
        System.out.println("Invoking getInfoList...");
        java.lang.String _getInfoList_sysName = "wkrj";
        java.lang.String _getInfoList_sysPass = "wkrj2015";
        java.lang.String _getInfoList_corpNo = "370783300004625";
        java.lang.String _getInfoList_sTime = "2014-04-03";
        java.lang.String _getInfoList_eTime = "2016-04-03";
        java.lang.String _getInfoList__return = port.getInfoList(_getInfoList_sysName, _getInfoList_sysPass, _getInfoList_corpNo, _getInfoList_sTime, _getInfoList_eTime);
        
        B2X b2x = new B2X();
        QueryResult qr =  (QueryResult)b2x.xml2Bean(_getInfoList__return, "QueryResult", QueryResult.class);
      
        System.out.println(jdbctemp+"===");
        
		if(qr!=null){
			System.out.println("baseinfo:");
			System.out.println("baseinfo.corpname:"+qr.getBaseInfo());
			System.out.println("baseinfo.corpcode:"+qr.getBaseInfo().getCorpcode());
			ArrayList<Production> productions=qr.getProductions();
			if(productions!=null){
				int i=0;
				for(Production production:productions){
					i++;
					System.out.println("production:"+i);
					System.out.println("production.orderno:"+production.getOrderno());
					System.out.println("production.dealername:"+production.getDealername());
					System.out.println("production.dealerno:"+production.getDealerno());
					System.out.println("production.ordertime:"+production.getOrdertime());
					System.out.println("production.chpname:"+production.getChpname());
					System.out.println("production.chpcode:"+production.getChpcode());
					System.out.println("production.salenum:"+production.getSalenum());
					System.out.println("production.guige:"+production.getGuige());
					
				}
			}
			
		}
        }

       // System.exit(0);
    }

}
