
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-10-13T14:16:26.584+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class WRServiceSoap_WRServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WRService");

    private WRServiceSoap_WRServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WRService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WRService ss = new WRService(wsdlURL, SERVICE_NAME);
        WRServiceSoap port = ss.getWRServiceSoap();  
        
        {
        System.out.println("Invoking getInfoList...");
        java.lang.String _getInfoList_sysName = "";
        java.lang.String _getInfoList_sysPass = "";
        java.lang.String _getInfoList_corpNo = "";
        java.lang.String _getInfoList_sTime = "";
        java.lang.String _getInfoList_eTime = "";
        java.lang.String _getInfoList__return = port.getInfoList(_getInfoList_sysName, _getInfoList_sysPass, _getInfoList_corpNo, _getInfoList_sTime, _getInfoList_eTime);
        System.out.println("getInfoList.result=" + _getInfoList__return);


        }

        System.exit(0);
    }

}
