package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-10-13T14:16:26.618+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WRServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WRServiceHttpPost {

    /**
     * 根据营业执照号、销售日期段获取购买记录信息
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetInfoList")
    public java.lang.String getInfoList(
        @WebParam(partName = "SysName", name = "SysName", targetNamespace = "http://tempuri.org/")
        java.lang.String sysName,
        @WebParam(partName = "SysPass", name = "SysPass", targetNamespace = "http://tempuri.org/")
        java.lang.String sysPass,
        @WebParam(partName = "CorpNo", name = "CorpNo", targetNamespace = "http://tempuri.org/")
        java.lang.String corpNo,
        @WebParam(partName = "STime", name = "STime", targetNamespace = "http://tempuri.org/")
        java.lang.String sTime,
        @WebParam(partName = "ETime", name = "ETime", targetNamespace = "http://tempuri.org/")
        java.lang.String eTime
    );
}
